// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw-VfEu8zodmgMa1bTtZioF54QNQdG8g4',
    appId: '1:584171821495:web:991a373bf1e04a3a3bf032',
    messagingSenderId: '584171821495',
    projectId: 'todo-app-mishait',
    authDomain: 'todo-app-mishait.firebaseapp.com',
    databaseURL: 'https://todo-app-mishait-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-mishait.appspot.com',
    measurementId: 'G-1P21Z02TL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4bomoiXM4KfXlv4mVzpUxwQRzZOTbaqc',
    appId: '1:584171821495:android:a2b3e9d4df30f8663bf032',
    messagingSenderId: '584171821495',
    projectId: 'todo-app-mishait',
    databaseURL: 'https://todo-app-mishait-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-mishait.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKe2pyVL4VItN2Bo7sFSj9SQUs-tqn0A4',
    appId: '1:584171821495:ios:5c93cd9a24674c793bf032',
    messagingSenderId: '584171821495',
    projectId: 'todo-app-mishait',
    databaseURL: 'https://todo-app-mishait-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-mishait.appspot.com',
    iosClientId: '584171821495-6h3l30ooeq3pr900shu3uqch2el3mpej.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationUtility',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKe2pyVL4VItN2Bo7sFSj9SQUs-tqn0A4',
    appId: '1:584171821495:ios:5c93cd9a24674c793bf032',
    messagingSenderId: '584171821495',
    projectId: 'todo-app-mishait',
    databaseURL: 'https://todo-app-mishait-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-mishait.appspot.com',
    iosClientId: '584171821495-6h3l30ooeq3pr900shu3uqch2el3mpej.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationUtility',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw-VfEu8zodmgMa1bTtZioF54QNQdG8g4',
    appId: '1:584171821495:web:41d9e77b4767710a3bf032',
    messagingSenderId: '584171821495',
    projectId: 'todo-app-mishait',
    authDomain: 'todo-app-mishait.firebaseapp.com',
    databaseURL: 'https://todo-app-mishait-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-mishait.appspot.com',
    measurementId: 'G-8W9QX1LWDX',
  );

}